"""make url field optional

Revision ID: 260474ed2ee0
Revises: ee1544a74ab8
Create Date: 2026-04-17 13:57:03.729148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '260474ed2ee0'
down_revision: Union[str, Sequence[str], None] = 'ee1544a74ab8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'url',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'url',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
    # ### end Alembic commands ###
