"""add currencie column to items

Revision ID: 7e647169f930
Revises: 260474ed2ee0
Create Date: 2026-04-20 14:54:39.507265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e647169f930'
down_revision: Union[str, Sequence[str], None] = '260474ed2ee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('currencie', sa.String(), server_default=sa.text("'usd'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'currencie')
    # ### end Alembic commands ###
