"""Add field is_notified to Item table

Revision ID: f805b81a6e8e
Revises: 6d6c3fa98a68
Create Date: 2026-04-30 13:52:02.355419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f805b81a6e8e'
down_revision: Union[str, Sequence[str], None] = '6d6c3fa98a68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('is_notified', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'is_notified')
    # ### end Alembic commands ###
